# Generated by Django 5.0.6 on 2024-05-21 23:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='assetId',
            new_name='asset_id',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='assetImage',
            new_name='asset_image',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='assetName',
            new_name='asset_name',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='assignDate',
            new_name='assign_date',
        ),
        migrations.AlterField(
            model_name='asset',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
