# Generated by Django 5.0.6 on 2024-05-21 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_users_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='block',
            new_name='is_blocked',
        ),
    ]
